site_name: crlngrlg
site_url: https://crlngrlg.github.io
repo_name: crlngrlg.github.io
repo_url: https://github.com/crlngrlg/crlngrlg.github.io
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.jpg
  favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Light mode
      primary: black
      accent: deep orange
      
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode
      primary: yellow
      accent: orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/crlngrlg
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/crlngrlg

copyright: Copyright &copy; 2025 crlngrlg